name: Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3
      - name: SetUp-DotNet7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          cache: true
      - name: Restore
        run: dotnet restore --locked-mode
      - name: Dotnet Build
        run: dotnet build MUS-MultiOnlineSpacesystem.sln
        
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3
      - name: SetUp-DotNet7
        uses: actions/setup-dotnet@v3-        
        with:
          dotnet-version: 7.x
          cache: true
      - run: dotnet test    
      
