name: Tests
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3
      - name: SetUp-DotNet7
        uses: actions/setup-dotnet@v3        
        with:
          dotnet-version: 7.x
      - run: dotnet test    
      
